version: '3.9' # Specify the version of Docker Compose

services:
  app: # Name of the service
    build:
      context: . # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile
    image: node-lts-app # Optional: name your image
    ports:
      - "3000:3000" # Map port 3000 on the host to port 3000 in the container
    volumes:
      - .:/app # Mount the current directory to the container for live updates
      - /app/node_modules # Avoid overwriting node_modules from the host
    environment:
      - NODE_ENV=production # Set environment variables

