name: Deploy Node.js Server

on:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 13.200.51.135 >> ~/.ssh/known_hosts

      - name: Deploy to AWS
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@13.200.51.135 << 'EOF'
            cd /var/www/express-server
            git pull origin main
            npm install
            pm2 restart my-app
          EOF

